[package]
name = "endlume"
version = "1.0.0-alpha.8.11"
description = "ENDLUME Studio"
authors = ["ENDLUME Studio"]
edition = "2021"

[lib]
name = "endlume_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
walkdir = "2"
sha2 = "0.10"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
parking_lot = "0.12"
anyhow = "1"
thiserror = "2"

sysinfo = "0.33"
tokio = { version = "1", features = ["time"] }
