import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!;const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Content-Type":"application/json","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type,apikey","Access-Control-Allow-Methods":"POST,OPTIONS"};const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const KEY_GROUPS=8;function group(){const b=crypto.getRandomValues(new Uint8Array(4));return [...b].map(x=>alphabet[x%alphabet.length]).join("")}function key(){return "ENDLUME-"+Array.from({length:KEY_GROUPS},()=>group()).join("-")}
async function hash(v:string){const a=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function admin(req:Request){const h=req.headers.get("authorization")||"";const token=h.toLowerCase().startsWith("bearer ")?h.slice(7):"";if(!token)return null;const {data}=await db.auth.getUser(token);if(!data.user)return null;const {data:a}=await db.from("endlume_admins").select("role").eq("user_id",data.user.id).maybeSingle();return a&&["owner","admin"].includes(a.role)?{user:data.user,role:String(a.role)}:null}
async function broadcast(topic:string,event:string,payload:unknown){if(!topic)return;try{await fetch(`${url}/realtime/v1/api/broadcast`,{method:"POST",headers:{"Content-Type":"application/json",apikey:service,Authorization:`Bearer ${service}`},body:JSON.stringify({messages:[{topic,event,payload,private:false}]})})}catch(e){console.error("broadcast",e)}}
async function licenseById(id:string){const {data}=await db.from("endlume_licenses").select("*").eq("id",id).maybeSingle();return data}
async function deviceById(id:string){const {data}=await db.from("endlume_devices").select("*").eq("id",id).maybeSingle();return data}
async function createLicense(b:any,actorRole:string){const plan=b.plan==="owner"?"owner":"managed";const owner=plan==="owner";if(owner&&actorRole!=="owner")return out({ok:false,code:"owner_required"},403);const max=Math.min(100,Math.max(1,Number(b.max_devices)||(owner?10:1)));let exp:null|string=null;if(!owner){const d=b.expires_at?new Date(String(b.expires_at)):new Date(Date.now()+30*86400000);if(Number.isNaN(d.getTime()))return out({ok:false,code:"expires_at"},400);exp=d.toISOString()}for(let i=0;i<5;i++){const k=key();const {data,error}=await db.from("endlume_licenses").insert({key_hash:await hash(k),key_prefix:"ENDLUME",key_last4:k.slice(-4),customer_name:b.customer_name?String(b.customer_name).slice(0,200):null,status:"active",plan,owner,expires_at:exp,max_devices:max,notes:b.notes?String(b.notes).slice(0,2000):null}).select("id,status,plan,owner,expires_at,max_devices,key_prefix,key_last4,realtime_topic,created_at,customer_name,notes").single();if(!error&&data)return out({ok:true,key:k,license:data});if(error?.code!=="23505")return out({ok:false,code:"create_failed"},500)}return out({ok:false,code:"collision"},500)}
async function mutateLicense(b:any){const id=String(b.license_id||"");const cur=await licenseById(id);if(!cur)return out({ok:false,code:"not_found"},404);const p:any={updated_at:new Date().toISOString()};const c=String(b.command||"");if(["active","paused","revoked"].includes(c))p.status=c;else if(c==="extend_7"||c==="extend_30"){if(cur.owner)return out({ok:false,code:"owner_lifetime"},409);const days=c==="extend_7"?7:30;const base=cur.expires_at&&Date.parse(cur.expires_at)>Date.now()?Date.parse(cur.expires_at):Date.now();p.expires_at=new Date(base+days*86400000).toISOString();if(cur.status==="expired")p.status="active"}else if(c==="set_expiration"){if(cur.owner)return out({ok:false,code:"owner_lifetime"},409);const d=new Date(String(b.expires_at||""));if(Number.isNaN(d.getTime()))return out({ok:false,code:"expires_at"},400);p.expires_at=d.toISOString();if(d.getTime()>Date.now()&&cur.status==="expired")p.status="active"}else return out({ok:false,code:"command"},400);const {data,error}=await db.from("endlume_licenses").update(p).eq("id",id).select("*").single();if(error||!data){console.error("ENDLUME admin update_failed",error);return out({ok:false,code:"update_failed"},500)}if(c==="revoked")await db.from("endlume_sessions").update({revoked_at:new Date().toISOString()}).eq("license_id",id).is("revoked_at",null);await broadcast(data.realtime_topic,"license_changed",{licenseId:id,status:data.status,expiresAt:data.expires_at,at:new Date().toISOString()});return out({ok:true,license:data})}
async function mutateDevice(b:any){const id=String(b.device_id||"");const device=await deviceById(id);if(!device)return out({ok:false,code:"device_not_found"},404);const lic=await licenseById(device.license_id);if(!lic)return out({ok:false,code:"license_not_found"},404);const c=String(b.command||"");const next=c==="block"?"blocked":c==="unblock"?"active":c==="detach"?"detached":"";if(!next)return out({ok:false,code:"command"},400);const stamp=new Date().toISOString();const {data,error}=await db.from("endlume_devices").update({status:next,updated_at:stamp,current_job_id:next==="active"?device.current_job_id:null,render_status:next==="active"?device.render_status:"blocked"}).eq("id",id).select("*").single();if(error||!data){console.error("ENDLUME admin device_update_failed",error);return out({ok:false,code:"device_update_failed"},500)}if(next!=="active")await db.from("endlume_sessions").update({revoked_at:stamp}).eq("device_id",id).is("revoked_at",null);await broadcast(lic.realtime_topic,"device_changed",{licenseId:lic.id,deviceId:id,status:next,at:stamp});return out({ok:true,device:data})}
async function dashboard(){const [l,d,r]=await Promise.all([db.from("endlume_licenses").select("id,key_prefix,key_last4,customer_name,status,plan,owner,created_at,updated_at,expires_at,max_devices,last_seen_at,notes,realtime_topic").order("created_at",{ascending:false}),db.from("endlume_devices").select("*").order("last_seen_at",{ascending:false}),db.from("endlume_renders").select("*").order("updated_at",{ascending:false}).limit(250)]);if(l.error||d.error||r.error){console.error("ENDLUME admin dashboard_failed",l.error||d.error||r.error);return out({ok:false,code:"dashboard_failed"},500)}return out({ok:true,licenses:l.data,devices:d.data,renders:r.data,serverTime:new Date().toISOString()})}
async function renderHistory(b:any){let q=db.from("endlume_renders").select("*").order("started_at",{ascending:false}).limit(Math.min(500,Math.max(1,Number(b.limit)||200)));if(b.license_id)q=q.eq("license_id",String(b.license_id));if(b.device_id)q=q.eq("device_id",String(b.device_id));const {data,error}=await q;if(error){console.error("ENDLUME admin history_failed",error);return out({ok:false,code:"history_failed"},500)}return out({ok:true,renders:data})}
async function renderEvents(b:any){const id=String(b.render_id||"");if(!id)return out({ok:false,code:"render_id"},400);const {data,error}=await db.from("endlume_render_events").select("*").eq("render_id",id).order("created_at",{ascending:true}).limit(1000);if(error){console.error("ENDLUME admin events_failed",error);return out({ok:false,code:"events_failed"},500)}return out({ok:true,events:data})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return out({ok:false,code:"method"},405);const len=Number(req.headers.get("content-length")||0);if(len>65536)return out({ok:false,code:"payload_too_large"},413);const actor=await admin(req);if(!actor)return out({ok:false,code:"admin_required"},403);let b:any;try{b=await req.json()}catch{return out({ok:false,code:"json"},400)}try{if(b.action==="create")return await createLicense(b,actor.role);if(b.action==="mutate")return await mutateLicense(b);if(b.action==="device")return await mutateDevice(b);if(b.action==="dashboard"||b.action==="list")return await dashboard();if(b.action==="render_history")return await renderHistory(b);if(b.action==="render_events")return await renderEvents(b);return out({ok:false,code:"action"},400)}catch(e){console.error("ENDLUME admin API",e);return out({ok:false,code:"internal"},500)}});
