import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useApp } from '../store';
import { api } from '../tauri';
import type { EffectPreset, SubscribePreset } from '../types';
import { Icon,Range } from '../components/ui';

const emptyEffect=(source=''):EffectPreset=>({
  id:crypto.randomUUID(),name:source.split(/[\\/]/).pop()||'Новый эффект',source,enabled:true,mode:'chromakey',keyColor:'#00ff00',similarity:.12,blend:.12,despill:1,
  lumaThreshold:.03,lumaTolerance:.08,saturation:1.2,x:.5,y:.5,scale:.34,fullscreen:false,previewFrameTime:0,startSec:0,endSec:null
});
const emptySubscribe=(source=''):SubscribePreset=>({...emptyEffect(source),name:source.split(/[\\/]/).pop()||'Subscribe',scale:.32,x:.16,y:.16,firstAtSec:10,secondAtSec:20,repeatEverySec:300});

export function EditorRouter(){
  const editor=useApp(s=>s.editor);if(!editor)return null;
  return editor.kind==='effects'?<EffectsEditor/>:<SubscribeEditor/>;
}

function EffectsEditor(){
  const effects=useApp(s=>s.effects),setEffects=useApp(s=>s.setEffects),openEditor=useApp(s=>s.openEditor),editor=useApp(s=>s.editor),draft=useApp(s=>s.draftProjects),projects=useApp(s=>s.projects);
  const [selected,setSelected]=useState(editor?.id||effects[0]?.id),[saved,setSaved]=useState(false);const current=effects.find(e=>e.id===selected);const [preview,setPreview]=useState('');const [previewBusy,setPreviewBusy]=useState(false);const persistTimer=useRef<number|undefined>(undefined);
  const projectPath=draft[0]?.path||projects.find(p=>p.status==='rendering')?.path||projects.at(-1)?.path;
  const saveLibrary=(next:EffectPreset[],immediate=false)=>{setEffects(next);if(persistTimer.current)window.clearTimeout(persistTimer.current);const persist=()=>api.saveLibrary({effects:next,subscribes:useApp.getState().subscribes,ambient:useApp.getState().ambient}).catch(()=>{});if(immediate)return persist();persistTimer.current=window.setTimeout(persist,320);return Promise.resolve()};
  useEffect(()=>()=>{if(persistTimer.current)window.clearTimeout(persistTimer.current)},[]);
  const add=async()=>{const source=await api.chooseVideo();if(!source)return;const e=emptyEffect(source);await saveLibrary([...effects,e],true);setSelected(e.id)};
  const patch=(p:Partial<EffectPreset>)=>current&&saveLibrary(effects.map(e=>e.id===current.id?{...e,...p}:e));
  const remove=async()=>{if(!current)return;const n=effects.filter(e=>e.id!==current.id);await saveLibrary(n,true);setSelected(n[0]?.id);setPreview('')};
  const refresh=async()=>{const latest=useApp.getState().effects.find(e=>e.id===selected);if(!projectPath||!latest)return;setPreviewBusy(true);try{const p=await api.generatePreview(projectPath,latest.previewFrameTime,useApp.getState().effects.filter(e=>e.enabled),[]);setPreview(api.previewUrl(p))}catch(e){await api.showError(`Не удалось создать предпросмотр эффекта.\n${String(e)}`)}finally{setPreviewBusy(false)}};
  useEffect(()=>{if(current&&projectPath){const t=window.setTimeout(()=>void refresh(),120);return()=>window.clearTimeout(t)}},[selected,current?.previewFrameTime,current?.mode,current?.keyColor,current?.similarity,current?.blend,current?.fullscreen,projectPath]);
  return <div className="editorPage"><EditorHeader title="Эффекты" subtitle="Live Preview • chromakey / luma / screen • постоянный кэш" onBack={()=>openEditor(null)}/><div className="editorLayout">
    <aside className="assetList"><button className="addAsset" onClick={add}>+ ДОБАВИТЬ</button>{effects.map(e=><button key={e.id} className={`assetItem ${selected===e.id?'active':''}`} onClick={()=>setSelected(e.id)}><span className="assetThumb"><Icon name="effects"/></span><span><b>{e.name}</b><small>{e.enabled?'Включён':'Выключен'} • {e.mode} • {e.cacheReady?'кэш готов':'кэш при первом рендере'}</small></span><i className={e.enabled?'enabled':'disabled'} title={e.enabled?'Выключить':'Включить'} onClick={ev=>{ev.stopPropagation();void saveLibrary(effects.map(x=>x.id===e.id?{...x,enabled:!x.enabled}:x),true)}}/></button>)}</aside>
    <main className="visualEditor">{current?<><PreviewStage title="ПРЕДПРОСМОТР" preview={preview} busy={previewBusy} current={current} onMove={(x,y)=>patch({x,y})} onScale={scale=>patch({scale})} onCommit={()=>window.setTimeout(()=>void refresh(),40)}/><div className="previewTime"><span>Кадр выбранного эффекта</span><Range value={current.previewFrameTime} min={0} max={60} step={.1} onChange={v=>patch({previewFrameTime:v})} minLabel="0:00" maxLabel="1:00"/><b>{current.previewFrameTime.toFixed(1)} сек</b></div><button className="refreshPreview" disabled={previewBusy} onClick={()=>void refresh()}><Icon name="refresh"/> {previewBusy?'ОБНОВЛЯЮ…':'ОБНОВИТЬ ПРЕДПРОСМОТР'}</button><Timeline start={current.startSec} end={current.endSec} total={(useApp.getState().settings.durationHours*3600)} onChange={(start,end)=>patch({startSec:start,endSec:end})}/></>:<div className="emptyEditor"><Icon name="effects"/><h3>Добавьте эффект</h3><p>Видео останется в библиотеке ENDLUME и будет доступно после перезапуска.</p></div>}</main>
    <aside className="editorControls">{current&&<><label>Название<input value={current.name} onChange={e=>patch({name:e.target.value})}/></label><label>Режим<select value={current.mode} onChange={e=>patch({mode:e.target.value as EffectPreset['mode']})}><option value="chromakey">Chromakey</option><option value="luma">Luma Alpha</option><option value="screen">Screen Blend</option></select></label>{current.mode==='chromakey'&&<><label>Цвет chromakey<input type="color" value={current.keyColor} onChange={e=>patch({keyColor:e.target.value})}/></label><SmallRange label="Similarity" value={current.similarity} min={.001} max={1} step={.001} onChange={v=>patch({similarity:v})}/><SmallRange label="Blend" value={current.blend} min={0} max={1} step={.01} onChange={v=>patch({blend:v})}/></>}{current.mode==='luma'&&<><SmallRange label="Threshold" value={current.lumaThreshold} min={0} max={1} step={.01} onChange={v=>patch({lumaThreshold:v})}/><SmallRange label="Tolerance" value={current.lumaTolerance} min={0} max={1} step={.01} onChange={v=>patch({lumaTolerance:v})}/></>}<label className="checkLine"><input type="checkbox" checked={current.fullscreen} onChange={e=>patch({fullscreen:e.target.checked})}/> На весь экран</label><p className="editorHint">Позиция и размер меняются сразу. FFmpeg-предпросмотр обновляется после отпускания мыши.</p><button className="savePreset" onClick={async()=>{await saveLibrary([...effects],true);setSaved(true);setTimeout(()=>setSaved(false),1200)}}><Icon name="save"/> {saved?'СОХРАНЕНО ✓':'СОХРАНИТЬ PRESET'}</button><button className="savePreset" onClick={()=>void saveLibrary(effects.map(e=>e.id===current.id?{...e,enabled:!e.enabled}:e),true)}>{current.enabled?'ВЫКЛЮЧИТЬ ЭФФЕКТ':'ВКЛЮЧИТЬ ЭФФЕКТ'}</button><button className="deletePreset" onClick={remove}><Icon name="trash"/> УДАЛИТЬ</button></>}</aside>
  </div></div>
}

function SubscribeEditor(){
  const subscribes=useApp(s=>s.subscribes),setSubscribes=useApp(s=>s.setSubscribes),openEditor=useApp(s=>s.openEditor),editor=useApp(s=>s.editor),draft=useApp(s=>s.draftProjects),projects=useApp(s=>s.projects);
  const [selected,setSelected]=useState(editor?.id||subscribes[0]?.id),[preview,setPreview]=useState(''),[previewBusy,setPreviewBusy]=useState(false),[saved,setSaved]=useState(false),persistTimer=useRef<number|undefined>(undefined);const current=subscribes.find(e=>e.id===selected);const projectPath=draft[0]?.path||projects.find(p=>p.status==='rendering')?.path||projects.at(-1)?.path;
  const saveLibrary=(next:SubscribePreset[],immediate=false)=>{setSubscribes(next);if(persistTimer.current)window.clearTimeout(persistTimer.current);const persist=()=>api.saveLibrary({effects:useApp.getState().effects,subscribes:next,ambient:useApp.getState().ambient}).catch(()=>{});if(immediate)return persist();persistTimer.current=window.setTimeout(persist,320);return Promise.resolve()};
  useEffect(()=>()=>{if(persistTimer.current)window.clearTimeout(persistTimer.current)},[]);
  const add=async()=>{const source=await api.chooseVideo();if(!source)return;const e=emptySubscribe(source);await saveLibrary([...subscribes,e],true);setSelected(e.id)};
  const patch=(p:Partial<SubscribePreset>)=>current&&saveLibrary(subscribes.map(e=>e.id===current.id?{...e,...p}:e));
  const remove=async()=>{if(!current)return;const n=subscribes.filter(e=>e.id!==current.id);await saveLibrary(n,true);setSelected(n[0]?.id);setPreview('')};
  const refresh=async()=>{const latest=useApp.getState().subscribes.find(e=>e.id===selected);if(!projectPath||!latest)return;setPreviewBusy(true);try{const p=await api.generatePreview(projectPath,latest.previewFrameTime,[],useApp.getState().subscribes.filter(s=>s.enabled));setPreview(api.previewUrl(p))}catch(e){await api.showError(`Не удалось создать предпросмотр Subscribe.\n${String(e)}`)}finally{setPreviewBusy(false)}};
  useEffect(()=>{if(current&&projectPath){const t=window.setTimeout(()=>void refresh(),120);return()=>window.clearTimeout(t)}},[selected,current?.previewFrameTime,current?.keyColor,current?.similarity,current?.blend,projectPath]);
  return <div className="editorPage"><EditorHeader title="Кнопка Subscribe" subtitle="Live Preview • chromakey • позиция • расписание" onBack={()=>openEditor(null)}/><div className="editorLayout">
    <aside className="assetList"><button className="addAsset" onClick={add}>+ ДОБАВИТЬ</button>{subscribes.map(e=><button key={e.id} className={`assetItem ${selected===e.id?'active':''}`} onClick={()=>setSelected(e.id)}><span className="assetThumb pink"><Icon name="subscribe"/></span><span><b>{e.name}</b><small>{e.enabled?'Включён':'Выключен'} • каждые {Math.round(e.repeatEverySec/60)} мин</small></span><i className={e.enabled?'enabled':'disabled'} title={e.enabled?'Выключить':'Включить'} onClick={ev=>{ev.stopPropagation();void saveLibrary(subscribes.map(x=>x.id===e.id?{...x,enabled:!x.enabled}:x),true)}}/></button>)}</aside>
    <main className="visualEditor">{current?<><PreviewStage title="ПРЕДПРОСМОТР" preview={preview} busy={previewBusy} current={current} onMove={(x,y)=>patch({x,y})} onScale={scale=>patch({scale})} onCommit={()=>window.setTimeout(()=>void refresh(),40)}/><div className="previewTime"><span>Кадр Subscribe-видео</span><Range value={current.previewFrameTime} min={0} max={60} step={.1} onChange={v=>patch({previewFrameTime:v})} minLabel="0:00" maxLabel="1:00"/><b>{current.previewFrameTime.toFixed(1)} сек</b></div><button className="refreshPreview" disabled={previewBusy} onClick={()=>void refresh()}><Icon name="refresh"/> {previewBusy?'ОБНОВЛЯЮ…':'ОБНОВИТЬ ПРЕДПРОСМОТР'}</button><SubscribeTimeline current={current} onChange={patch}/></>:<div className="emptyEditor"><Icon name="subscribe"/><h3>Добавьте Subscribe-видео</h3></div>}</main>
    <aside className="editorControls">{current&&<><label>Название<input value={current.name} onChange={e=>patch({name:e.target.value})}/></label><label>Цвет chromakey<input type="color" value={current.keyColor} onChange={e=>patch({keyColor:e.target.value})}/></label><SmallRange label="Similarity" value={current.similarity} min={.001} max={1} step={.001} onChange={v=>patch({similarity:v})}/><SmallRange label="Blend" value={current.blend} min={0} max={1} step={.01} onChange={v=>patch({blend:v})}/><div className="schedule"><label>Первое появление<input type="number" value={current.firstAtSec} onChange={e=>patch({firstAtSec:+e.target.value})}/><small>сек</small></label><label>Второе появление<input type="number" value={current.secondAtSec} onChange={e=>patch({secondAtSec:+e.target.value})}/><small>сек</small></label><label>Затем каждые<input type="number" value={Math.round(current.repeatEverySec/60)} onChange={e=>patch({repeatEverySec:+e.target.value*60})}/><small>мин</small></label></div><p className="editorHint">Позиция и размер меняются сразу. Предпросмотр обновляется после отпускания мыши.</p><button className="savePreset" onClick={async()=>{await saveLibrary([...subscribes],true);setSaved(true);setTimeout(()=>setSaved(false),1200)}}><Icon name="save"/> {saved?'СОХРАНЕНО ✓':'СОХРАНИТЬ PRESET'}</button><button className="savePreset" onClick={()=>void saveLibrary(subscribes.map(e=>e.id===current.id?{...e,enabled:!e.enabled}:e),true)}>{current.enabled?'ВЫКЛЮЧИТЬ SUBSCRIBE':'ВКЛЮЧИТЬ SUBSCRIBE'}</button><button className="deletePreset" onClick={remove}><Icon name="trash"/> УДАЛИТЬ</button></>}</aside>
  </div></div>
}

function EditorHeader({title,subtitle,onBack}:{title:string;subtitle:string;onBack:()=>void}){return <div className="editorHeader"><div><small>ENDLUME</small><h1>{title}</h1><p>{subtitle}</p></div><button onClick={onBack}>← ВЕРНУТЬСЯ К ПРОЕКТУ</button></div>}

function PreviewStage({title,preview,busy,current,onMove,onScale,onCommit}:{title:string;preview:string;busy:boolean;current:EffectPreset;onMove:(x:number,y:number)=>void;onScale:(v:number)=>void;onCommit?:()=>void}){
  const ref=useRef<HTMLDivElement>(null),drag=useRef(false),resize=useRef(false),raf=useRef<number|undefined>(undefined),lastPointer=useRef<globalThis.PointerEvent|undefined>(undefined),currentRef=useRef(current),moveRef=useRef(onMove),scaleRef=useRef(onScale),commitRef=useRef(onCommit);
  currentRef.current=current;moveRef.current=onMove;scaleRef.current=onScale;commitRef.current=onCommit;
  useEffect(()=>{const apply=()=>{raf.current=undefined;const e=lastPointer.current,el=ref.current;if(!e||!el)return;const r=el.getBoundingClientRect(),c=currentRef.current;if(drag.current)moveRef.current(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)));if(resize.current){const cx=r.left+c.x*r.width,cy=r.top+c.y*r.height;const d=Math.hypot(e.clientX-cx,e.clientY-cy)/(Math.min(r.width,r.height)*.65);scaleRef.current(Math.max(.05,Math.min(2,d)))}};const move=(e:globalThis.PointerEvent)=>{if(!drag.current&&!resize.current)return;lastPointer.current=e;if(raf.current==null)raf.current=requestAnimationFrame(apply)};const up=()=>{const changed=drag.current||resize.current;drag.current=false;resize.current=false;if(raf.current!=null){cancelAnimationFrame(raf.current);raf.current=undefined;apply()}if(changed)commitRef.current?.()};window.addEventListener('pointermove',move,{passive:true});window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);if(raf.current!=null)cancelAnimationFrame(raf.current)}},[]);
  const size:React.CSSProperties=current.fullscreen?{left:'0%',top:'0%',width:'100%',height:'100%',transform:'none',touchAction:'none'}:{left:`${current.x*100}%`,top:`${current.y*100}%`,width:`${Math.max(10,current.scale*65)}%`,aspectRatio:'16 / 9',transform:'translate(-50%,-50%)',touchAction:'none',willChange:'left, top, width'};
  return <div className="previewStage" ref={ref}><div className="previewLabel">{title}</div>{preview?<video key={preview} src={preview} autoPlay loop muted controls playsInline/>:<div className="previewPlaceholder"><Icon name="image"/><span>{busy?'Создаю быстрый предпросмотр…':'Выберите проект на основном экране'}</span></div>}<div className="draggableOverlay" style={size} onPointerDown={(e:React.PointerEvent<HTMLDivElement>)=>{if(current.fullscreen)return;e.preventDefault();drag.current=true}}><i className="corner nw"/><i className="corner ne"/><i className="corner sw"/><i className="corner se" onPointerDown={e=>{e.preventDefault();e.stopPropagation();drag.current=false;resize.current=true}}/></div>{busy&&<div className="previewBusy">Обновляю preview…</div>}</div>
}

function SmallRange({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void}){return <div className="smallRange"><div><span>{label}</span><b>{value.toFixed(2)}</b></div><Range value={value} min={min} max={max} step={step} onChange={onChange}/></div>}

function Timeline({start,end,total,onChange}:{start:number;end:number|null;total:number;onChange:(s:number,e:number|null)=>void}){const safeEnd=end??total;return <div className="timeline"><div className="timelineHead"><b>ВРЕМЯ ЭФФЕКТА</b><span>{Math.round(start)} сек → {end==null?'до конца':`${Math.round(end)} сек`}</span></div><div className="dualRange"><Range value={start} min={0} max={total} step={1} onChange={v=>onChange(Math.min(v,safeEnd-1),end)} minLabel="0:00" maxLabel="конец видео"/><Range value={safeEnd} min={0} max={total} step={1} onChange={v=>onChange(start,v>=total?null:Math.max(v,start+1))} minLabel="начало" maxLabel="до конца"/></div></div>}

function SubscribeTimeline({current,onChange}:{current:SubscribePreset;onChange:(p:Partial<SubscribePreset>)=>void}){const total=useApp(s=>s.settings.durationHours*3600);const marks=useMemo(()=>{const a=[current.firstAtSec,current.secondAtSec];for(let t=current.secondAtSec+current.repeatEverySec;t<total;t+=current.repeatEverySec)a.push(t);return a},[current.firstAtSec,current.secondAtSec,current.repeatEverySec,total]);return <div className="timeline subscribeTimeline"><div className="timelineHead"><b>РАСПИСАНИЕ SUBSCRIBE</b><span>{marks.length} показов</span></div><div className="timeTrack">{marks.map((m,i)=><i key={i} style={{left:`${(m/total)*100}%`}} title={`${Math.floor(m/60)}:${String(Math.round(m%60)).padStart(2,'0')}`}/>)}</div></div>}
