import React, { useEffect, useState } from 'react';
import { api, type SingleAppStatus } from '../tauri';
import type { BenchmarkResult, LicenseStatus } from '../types';
import { ReleaseHistory } from '../components/ReleaseHistory';
import { IS_WINDOWS, PRODUCT_KICKER, PRODUCT_NAME } from '../platform-brand';

type Tab='general'|'engine'|'updates'|'about';
export function SettingsPage(){
  const [appVersion,setAppVersion]=useState('');
  const [tab,setTab]=useState<Tab>('general'),[license,setLicense]=useState<LicenseStatus>({valid:false}),[key,setKey]=useState(''),[bench,setBench]=useState<BenchmarkResult>(),[busy,setBusy]=useState(false),[update,setUpdate]=useState<any>(),[updateProgress,setUpdateProgress]=useState<number|null>(null),[cache,setCache]=useState<{count:number;bytes:number}>({count:0,bytes:0}),[appGuard,setAppGuard]=useState<SingleAppStatus>();
  useEffect(()=>{api.appVersion().then(setAppVersion).catch(()=>{});api.license().then(setLicense).catch(()=>setLicense({valid:false}));api.cacheStats().then(setCache).catch(()=>{});if(!IS_WINDOWS)api.cleanupDuplicateApps(false).then(setAppGuard).catch(()=>{})},[]);
  const checkUpdate=async()=>{
    if(busy)return;setBusy(true);setUpdateProgress(null);
    try{const u=await api.checkUpdate();if(u?.version){window.dispatchEvent(new CustomEvent('endlume-update-found',{detail:u}));setUpdate(undefined)}else{setUpdate(u||{none:true})}}
    catch(e){setUpdate({error:String(e)});await api.showError(`Не удалось проверить обновление ${PRODUCT_NAME}: ${String(e)}`)}finally{setBusy(false)}
  };
  const installUpdate=async()=>{
    if(busy||!update?.install)return;setBusy(true);setUpdateProgress(0);
    try{await update.install((p:number)=>setUpdateProgress(p))}
    catch(e){setUpdateProgress(null);setUpdate({error:String(e)});await api.showError(`Не удалось установить ${PRODUCT_NAME}: ${String(e)}`)}finally{setBusy(false)}
  };
  const cleanDuplicates=async()=>{
    if(busy||IS_WINDOWS)return;setBusy(true);try{const result=await api.cleanupDuplicateApps(true);setAppGuard(result);if(result.failed?.length)await api.showError(`Не удалось удалить ${result.failed.length} коп. ENDLUME.\n${result.failed.map(x=>`${x.path}: ${x.error}`).join('\n')}`)}catch(e){await api.showError(String(e))}finally{setBusy(false)}
  };
  const normalizeName=async()=>{
    if(busy||IS_WINDOWS)return;setBusy(true);try{await api.normalizeAppName()}catch(e){setBusy(false);await api.showError(`Не удалось закрепить ENDLUME Studio в /Applications.\n${String(e)}`)}
  };
  const appHealthy=appGuard?.singleApp&&appGuard?.canonicalInstall!==false;
  return <div className="simplePage settingsPage"><div className="simpleHeader"><div><small>{PRODUCT_KICKER}</small><h1>Настройки</h1><p>Обновления, лицензия, Fast Engine и информация о программе.</p></div></div><div className="settingsTabs">{(['general','engine','updates','about'] as Tab[]).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='general'?'ОБЩИЕ':t==='engine'?'FAST ENGINE':t==='updates'?'ОБНОВЛЕНИЯ':'О ПРОГРАММЕ'}</button>)}</div>
    {tab==='general'&&<div className="settingsCard"><h3>Лицензия</h3><div className="licenseStatus"><i className={license.valid?'ok':'bad'}/><div><b>{license.valid?'ENDLUME активирована':'Нужна активация'}</b><small>{license.type==='owner-lifetime'?'Бессрочная лицензия владельца':license.type==='monthly'?'Месячная лицензия':license.type==='development'?'Development build':'Лицензия не найдена'}</small></div></div>{!license.valid&&<div className="activationLine"><input placeholder="Введите ключ ENDLUME" value={key} onChange={e=>setKey(e.target.value)}/><button onClick={async()=>{try{setLicense(await api.activate(key))}catch(e){await api.showError(String(e))}}}>АКТИВИРОВАТЬ</button></div>}<p className="settingsNote">Рендер выполняется локально. Windows и macOS используют интернет для проверки лицензии, heartbeat состояния устройства, статуса и прогресса ENDLUME-рендеров и обновлений. Сторонние приложения и документы не мониторятся.</p></div>}
    {tab==='engine'&&<div className="settingsCard"><h3>ENDLUME Fast Engine</h3><p>Benchmark проверяет комплектный FFmpeg, реально кодирует короткий тестовый MP4 каждым движком и выбирает только тот кодировщик, который действительно отработал на этой системе.</p><button className="settingsAction" disabled={busy} onClick={async()=>{setBusy(true);setBench(undefined);try{setBench(await api.benchmark())}catch(e){await api.showError(`Benchmark не запустился.\n${String(e)}`)}finally{setBusy(false)}}}>{busy?'ПРОВЕРЯЮ ДВИЖКИ…':'ЗАПУСТИТЬ BENCHMARK'}</button>{bench&&<div className="bench"><b style={{color:bench.selected?'#dff7eb':'#ff8fa2'}}>{bench.selected?`Выбран: ${bench.selected}`:'Рабочий кодировщик не найден'}</b><small style={{display:'block',marginTop:5,color:'#78829e'}}>Система: {bench.platform}{bench.arch?` • ${bench.arch}`:''}{bench.ffmpegProbeOk===false?' • FFmpeg probe: ошибка':''}</small>{bench.ffmpegProbeError&&<p style={{fontSize:9,color:'#ff8fa2',lineHeight:1.45}}>{bench.ffmpegProbeError}</p>}{bench.candidates.map(x=><div key={x.encoder} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:'4px 14px',alignItems:'center',padding:'10px 0'}}><span><b style={{fontSize:11}}>{x.encoder}</b><small style={{display:'block',marginTop:3,color:x.ok?'#6f8a80':'#9a7180',fontSize:9,lineHeight:1.4}}>{x.note||(!x.listed?'Кодировщик отсутствует в FFmpeg':'Не прошёл реальный encode-test')}</small></span><em className={x.ok?'ok':'bad'}>{x.ok?`${x.seconds?.toFixed(2)||'?'} сек`:x.listed===false?'нет в FFmpeg':'ошибка'}</em></div>)}</div>}<p className="settingsNote">Кэш Effects: {cache.count} файлов • {(cache.bytes/1024/1024).toFixed(1)} МБ. Значение 0 файлов нормально, пока ни один эффект ещё не был подготовлен к рендеру.</p></div>}
    {tab==='updates'&&<div className="settingsCard"><h3>Обновления</h3><p>{PRODUCT_NAME} {appVersion||'…'}</p><p className="settingsNote">Подписанные обновления проверяются и устанавливаются через интернет внутри приложения. Terminal, GitHub CLI и ручная сборка пользователю не нужны.</p><button className="settingsAction" disabled={busy} onClick={checkUpdate}>{busy&&updateProgress===null?'ПРОВЕРЯЮ…':'ПРОВЕРИТЬ ОБНОВЛЕНИЯ'}</button>{updateProgress!==null&&<div className="updateProgress"><i style={{width:`${updateProgress}%`}}/><span>{updateProgress.toFixed(0)}%</span></div>}{update?.none&&<div><p className="updateOk">Установлена актуальная версия: {update.current||appVersion||'…'}.</p></div>}{update?.version&&<div className="updateFound"><b>Доступна {PRODUCT_NAME} {update.version}</b>{update.date&&<small>{String(update.date)}</small>}<p>{update.body}</p><button className="settingsAction" disabled={busy} onClick={installUpdate}>{busy&&updateProgress!==null?`СКАЧИВАЮ ${updateProgress.toFixed(0)}%`:'ОБНОВИТЬ'}</button><p className="settingsNote">Скачивается готовая подписанная сборка. Локальная компиляция пользователю не требуется.</p></div>}{update?.error&&<p className="updateError">Ошибка обновления: {update.error}</p>}
      {!IS_WINDOWS&&<div className="whatsNew"><h4>SINGLE APP GUARD</h4><p className={appHealthy?'updateOk':'settingsNote'}>{appGuard?.supported===false?'На этой системе не требуется.':appHealthy?'✓ Одна установка: /Applications/ENDLUME YT Studio PEISOV.app. Клоны будут удаляться автоматически.':appGuard?.canonicalInstall===false?`ENDLUME запущена не из канонического места. Нужно: /Applications/ENDLUME YT Studio PEISOV.app.`:appGuard?`Найдено копий: ${appGuard.remaining?.length||appGuard.found?.length||0}. Текущая: ${appGuard.currentPath||'—'}`:'Проверяю приложения…'}</p>{appGuard?.supported!==false&&appGuard?.canonicalInstall===false&&<button className="settingsAction" disabled={busy} onClick={normalizeName}>ЗАКРЕПИТЬ В /APPLICATIONS КАК ENDLUME YT STUDIO PEISOV</button>}{appGuard?.supported!==false&&!appGuard?.singleApp&&<button className="settingsAction" disabled={busy} onClick={cleanDuplicates}>УДАЛИТЬ КЛОНЫ ENDLUME</button>}{appGuard?.currentPath&&<p className="settingsNote">Текущее приложение: {appGuard.currentPath}</p>}<ReleaseHistory currentVersion={appVersion}/></div>}</div>}
    {tab==='about'&&<div className="settingsCard about"><div className="aboutLogo"><span className="infinity"><i/><i/></span></div><h2>{PRODUCT_NAME}</h2><p>Long Video Engine</p><div className="aboutRows"><span>Версия <b>{appVersion||'…'}</b></span><span>Обновлено <b>01.10.2026</b></span>{IS_WINDOWS?<span>Windows <b>10 / 11 x64</b></span>:<span>macOS <b>Apple Silicon M1+</b></span>}<span>Render Core <b>Rust + FFmpeg</b></span><span>UI <b>Tauri 2</b></span><span>Создатель <b>Kirill Peisov</b></span><span>Email <b>peisov.business@gmail.com</b></span></div></div>}
  </div>
}