#!/usr/bin/env python3
from pathlib import Path
import json,re
VERSION='1.0.0-alpha.8.45'
ROOT=Path(__file__).resolve().parent.parent

def need(rel):
 p=ROOT/rel
 if not p.is_file(): raise SystemExit(f'8.45: missing {rel}')
 return p

def must(c,m):
 if not c: raise SystemExit('8.45: '+m)

p=need('src-tauri/src/render.rs');r=p.read_text(encoding='utf-8')
must('"-count_packets"' in r,'8.43 full-file packet scan marker missing');must('nb_read_packets' in r,'8.43 packet-count marker missing');must('Финальная проверка FFprobe' in r,'final FFprobe stage missing')
for m in ['resolved_job.settings.fps=if resolved_job.settings.fps>=50{60}else{30};','fn cfr_output_args(','"-fps_mode".into(),"cfr".into()','"-c:v","copy","-c:a","copy","-video_track_timescale","60000"','fn hybrid_video_kbps(_s:&RenderSettings)->u64{500}','force_original_aspect_ratio=increase','materialize_continuous_audio','acrossfade=d={cf}:c1=tri:c2=tri']: must(m in r,'protected 8.44 invariant missing before patch: '+m)
start=r.find('async fn verify_result(');end=r.find('\n\npub async fn render_job',start);must(start>=0 and end>start,'verify_result block missing')
new_verify=r'''#[derive(Debug,Clone)]
struct FinalProbe{video_bitrate:Option<u64>}
fn final_verify_error(msg:impl Into<String>)->String{format!("FINAL_VERIFY: {}",msg.into())}
async fn ffprobe_output_timeout(app:&AppHandle,args:Vec<String>,timeout:Duration)->Result<(Vec<u8>,Vec<u8>),String>{
 let (mut rx,child)=app.shell().sidecar("ffprobe").map_err(|e|e.to_string())?.args(args).spawn().map_err(|e|e.to_string())?;let mut child=Some(child);let started=Instant::now();let mut stdout=Vec::new();let mut stderr=Vec::new();
 loop{if started.elapsed()>=timeout{if let Some(c)=child.take(){let _=c.kill();}return Err(format!("FFprobe timeout after {:.1}s",timeout.as_secs_f64()))}let wait=timeout.saturating_sub(started.elapsed()).min(Duration::from_millis(200));let ev=match tokio::time::timeout(wait,rx.recv()).await{Err(_)=>continue,Ok(Some(v))=>v,Ok(None)=>return Err("FFprobe закрыл канал без статуса завершения".into())};match ev{CommandEvent::Stdout(b)=>stdout.extend_from_slice(&b),CommandEvent::Stderr(b)=>stderr.extend_from_slice(&b),CommandEvent::Error(e)=>{if let Some(c)=child.take(){let _=c.kill();}return Err(e)},CommandEvent::Terminated(t)=>{child.take();if t.code.unwrap_or(1)!=0{return Err(if stderr.is_empty(){format!("FFprobe завершился с кодом {:?}",t.code)}else{String::from_utf8_lossy(&stderr).trim().to_string()})}return Ok((stdout,stderr))},_=>{}}}
}
fn jnum(v:Option<&serde_json::Value>)->Option<f64>{match v{Some(serde_json::Value::Number(n))=>n.as_f64(),Some(serde_json::Value::String(s))=>s.parse().ok(),_=>None}}
fn ju64(v:Option<&serde_json::Value>)->Option<u64>{match v{Some(serde_json::Value::Number(n))=>n.as_u64(),Some(serde_json::Value::String(s))=>s.parse().ok(),_=>None}}
fn rate(s:&str)->f64{let mut p=s.split('/');let a=p.next().and_then(|x|x.parse::<f64>().ok()).unwrap_or(0.0);let b=p.next().and_then(|x|x.parse::<f64>().ok()).unwrap_or(1.0).max(0.000001);a/b}
async fn verify_result_once(app:&AppHandle,out:&Path,expected:f64,s:&RenderSettings)->Result<FinalProbe,String>{
 let args=vec!["-v","error","-show_entries","format=duration:stream=codec_type,width,height,r_frame_rate,avg_frame_rate,nb_frames,duration,bit_rate","-of","json",out.to_string_lossy().as_ref()].into_iter().map(String::from).collect();let (stdout,_)=ffprobe_output_timeout(app,args,Duration::from_secs(12)).await?;let root:serde_json::Value=serde_json::from_slice(&stdout).map_err(|e|format!("FFprobe JSON: {e}"))?;let d=jnum(root.get("format").and_then(|x|x.get("duration"))).ok_or("FFprobe не вернул длительность")?;if (d-expected).abs()>4.0{return Err(format!("Неверная длительность: {:.1} сек вместо {:.1}",d,expected))}let streams=root.get("streams").and_then(|x|x.as_array()).ok_or("FFprobe не вернул streams")?;let v=streams.iter().find(|x|x.get("codec_type").and_then(|x|x.as_str())==Some("video")).ok_or("Нет видеопотока")?;let a=streams.iter().find(|x|x.get("codec_type").and_then(|x|x.as_str())==Some("audio")).ok_or("Нет аудиодорожки")?;let w=v.get("width").and_then(|x|x.as_u64()).unwrap_or(0) as u32;let h=v.get("height").and_then(|x|x.as_u64()).unwrap_or(0) as u32;if w!=s.width||h!=s.height{return Err(format!("Неверное разрешение: {}x{} вместо {}x{}",w,h,s.width,s.height))}let rf=rate(v.get("r_frame_rate").and_then(|x|x.as_str()).unwrap_or("0/1"));let af=rate(v.get("avg_frame_rate").and_then(|x|x.as_str()).unwrap_or("0/1"));let wanted=if s.fps>=50{60.0}else{30.0};if (rf-wanted).abs()>0.10||(af-wanted).abs()>0.10||(rf-af).abs()>0.10{return Err(format!("Ошибка FPS: {:.3}/{:.3}, ожидалось {:.0}",rf,af,wanted))}if let (Some(fr),Some(sd))=(jnum(v.get("nb_frames")),jnum(v.get("duration"))){if fr>0.0&&sd>0.5{let measured=fr/sd;if (measured-wanted).abs()>0.30{return Err(format!("Ошибка FPS metadata: {:.3}",measured))}}}if let Some(ad)=jnum(a.get("duration")){if ad>0.0&&(ad-d).abs()>4.5{return Err(format!("Длительность аудио {:.1} сек не совпадает с контейнером {:.1}",ad,d))}}Ok(FinalProbe{video_bitrate:ju64(v.get("bit_rate"))})
}
async fn verify_result(app:&AppHandle,out:&Path,expected:f64,s:&RenderSettings)->Result<FinalProbe,String>{let mut last=String::new();for n in 1..=2{match verify_result_once(app,out,expected,s).await{Ok(v)=>return Ok(v),Err(e)=>{last=e;if n<2{tokio::time::sleep(Duration::from_millis(250)).await}}}}Err(final_verify_error(last))}'''
r=r[:start]+new_verify+r[end:]
must(r.count('let result:Result<(Vec<f64>,f64),String>=async{')==1,'render result tuple marker not unique');r=r.replace('let result:Result<(Vec<f64>,f64),String>=async{','let result:Result<(Vec<f64>,f64,Option<u64>),String>=async{',1)
pat=re.compile(r'emit_progress\(app,job,started,&timer,97\.0,"Финальная проверка FFprobe",&encoder,attempt,None\);verify_result\(app,&out,final_duration,&job\.settings\)\.await\?;(?P<middle>.*?)Ok\(\(durations,final_duration\)\)',re.S);m=pat.search(r);must(m is not None,'8.44 final verify sequence not found structurally');mid=m.group('middle');replacement='let verify_mark=Instant::now();emit_progress(app,job,started,&timer,97.0,"Финальная проверка FFprobe",&encoder,attempt,None);let final_probe=verify_result(app,&out,final_duration,&job.settings).await?;emit_timing(app,&job.project.id,"final-verify",verify_mark.elapsed().as_secs_f64());emit_progress(app,job,started,&timer,99.0,"Финализация результата",&encoder,attempt,None);let finalize_mark=Instant::now();'+mid+'emit_timing(app,&job.project.id,"finalize",finalize_mark.elapsed().as_secs_f64());Ok((durations,final_duration,final_probe.video_bitrate))';r=pat.sub(lambda _:replacement,r,count=1)
pat_done=re.compile(r'Ok\(\(_durations,_fd\)\)=>\{let bytes=std::fs::metadata\(&out\)\.ok\(\)\.map\(\|m\|m\.len\(\)\);let bitrate=probe_video_bitrate\(app,&out\)\.await;');must(pat_done.search(r) is not None,'post-verify bitrate probe sequence missing');r=pat_done.sub('Ok((_durations,_fd,bitrate))=>{let bytes=std::fs::metadata(&out).ok().map(|m|m.len());',r,count=1)
pat_retry=re.compile(r'if last_error==CANCELLED\{return Err\(last_error\)\}if attempt<2\{emit_progress\(app,job,started,&timer,2\.0,"[^"]+",&encoder,attempt\+1,None\);\}');must(pat_retry.search(r) is not None,'render retry marker missing');r=pat_retry.sub('if last_error==CANCELLED{return Err(last_error)}if last_error.starts_with("FINAL_VERIFY:"){return Err(last_error.trim_start_matches("FINAL_VERIFY: ").to_string())}if attempt<2{emit_progress(app,job,started,&timer,2.0,"Ошибка рендера — резервный движок",&encoder,attempt+1,None);}',r,count=1)
for bad in ['"-count_packets"','nb_read_packets','let bitrate=probe_video_bitrate(app,&out).await;']: must(bad not in r,'slow finalization marker survived: '+bad)
for good in ['ffprobe_output_timeout','Duration::from_secs(12)','final-verify','Финализация результата','resolved_job.settings.fps=if resolved_job.settings.fps>=50{60}else{30};','fn cfr_output_args(','"-fps_mode".into(),"cfr".into()','"-c:v","copy","-c:a","copy","-video_track_timescale","60000"','fn hybrid_video_kbps(_s:&RenderSettings)->u64{500}','force_original_aspect_ratio=increase','materialize_continuous_audio','acrossfade=d={cf}:c1=tri:c2=tri']: must(good in r,'post-patch invariant missing: '+good)
p.write_text(r,encoding='utf-8')
for rel in ['package.json','src-tauri/Cargo.toml','src-tauri/tauri.conf.json','src/tauri.ts','src/pages/SettingsPage.tsx','src/pages/App.tsx']:
 q=need(rel);s=q.read_text(encoding='utf-8');s=re.sub(r'1\.0\.0-alpha\.8\.\d+',VERSION,s);q.write_text(s,encoding='utf-8')
q=need('src/components/ReleaseHistory.tsx');h=q.read_text(encoding='utf-8').replace('current:true,','current:false,');entry="""  {version:'1.0.0-alpha.8.45',date:'03.09.2026',current:true,title:'Fast Finalize Hotfix',items:['97% FFprobe больше не сканирует все пакеты двухчасового видео.','Финальная проверка — metadata-only, timeout 12 секунд, один локальный retry.','Отдельный blocking bitrate probe удалён; ошибка проверки не запускает повторный полный рендер.','Кодек, качество, музыка, Effects/Subscribe, 30/60 FPS и VYRON Bridge не изменены.']},
""";anchor='const releases:Release[]=[\n'
if "version:'1.0.0-alpha.8.45'" not in h: must(anchor in h,'release history anchor missing');h=h.replace(anchor,anchor+entry,1)
q.write_text(h,encoding='utf-8');print('ENDLUME 8.45 fast finalization hotfix: PASS')
