from pathlib import Path

p = Path("src/pages/Editors.tsx")
text = p.read_text(encoding="utf-8")

# Fix the timing width template generated by the Smart Align patch.
text = text.replace(
    "Math.max(0,((safeEnd-start)/Math.max(1,total))*100))}%",
    "Math.max(0,((safeEnd-start)/Math.max(1,total))*100)}%",
)

# Hard fail before TypeScript if the generated editor is incomplete.
required = [
    "smartAlignToolbar",
    "smartGuideLayer",
    "smartSafeArea",
    "smartTimingSummary",
    "АВТОЦЕНТР",
    "Shift + drag",
    "effects-v4-aspect-safe" if Path("src-tauri/src/cache.rs").exists() else "smartAlignStage",
]
for marker in required:
    targets = text
    if marker == "effects-v4-aspect-safe":
        targets = Path("src-tauri/src/cache.rs").read_text(encoding="utf-8")
    if marker not in targets:
        raise SystemExit(f"Smart Align validation failed: missing {marker}")

if "shiftKey?.02" in text or "*100))}%" in text:
    raise SystemExit("Smart Align validation failed: invalid generated TypeScript remains")

p.write_text(text, encoding="utf-8")
print("ENDLUME alpha.8.24 Smart Align post-check passed")
