import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './pages/App';
import './styles.css';
import './nav-polish.css';
import './project-polish.css';
import './motion-polish.css';
import './motion-interactions.css';
import './chroma-fidelity.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
